/**
 * Environment parsing and validation.
 *
 * Every rule here fails closed: a malformed value stops the process rather than
 * falling back to something permissive. That is a stated design property, not a
 * preference — PLAN-v3 §3.3 lists the startup assertions that turn a bad
 * deployment into a loud failure instead of a silently open service, and T-C6
 * is the test for the origin allowlist specifically.
 *
 * The error messages name the offending variable. "refuses to start" is only
 * useful during an incident if the operator can tell which line to fix.
 */

/** A configuration value that failed validation. */
export class ConfigError extends Error {
  constructor(
    readonly variable: string,
    message: string,
  ) {
    super(`${variable}: ${message}`);
    this.name = "ConfigError";
  }
}

/** The api's validated runtime configuration. */
export interface ApiConfig {
  /** Exact origins allowed to call this API. Never empty, never a wildcard. */
  readonly allowedOrigins: ReadonlySet<string>;
  /** Secret for deriving per-session CSRF keys. Base64url, exactly 43 chars. */
  readonly csrfKey: string;
  /** How long a session and its artifacts survive. */
  readonly sessionTtlHours: number;
  /** Refuse to start an export below this much free disk. */
  readonly minFreeDiskMb: number;
  /** Base URL of the orchestrator. Internal only. */
  readonly orchestratorUrl: string;
  /** HMAC secret for signed internal calls. */
  readonly orchestratorSecret: string;
  /** Replay window for internal calls, in seconds. */
  readonly orchestratorReplayWindowSeconds: number;
  /** Log level. */
  readonly logLevel: "debug" | "info" | "warn" | "error";
  /** Listen address for the HTTP surface. */
  readonly listen: string;
  /** Path to the SQLite database file. */
  readonly databasePath: string;
  /** SSE ring buffer size, in events. */
  readonly sseBufferEvents: number;
  /** SSE keepalive interval, in milliseconds. */
  readonly sseKeepaliveMs: number;
}

/**
 * secretPattern is the session secret's exact shape: 43 base64url characters,
 * which is 32 bytes unpadded.
 *
 * Enforced mechanically rather than trusted from the client, because under the
 * two-component split the secret is generated by Component A (PLAN-v3 §4) and a
 * compromised frontend could generate a weak one. The API is the last place that
 * can say no.
 */
const SECRET_PATTERN = /^[A-Za-z0-9_-]{43}$/;

/**
 * validateOrigins checks the ALLOWED_ORIGINS value against every rule in
 * PLAN-v3 §3.3.
 *
 * Rejects: empty, `*`, `null`, non-https, trailing slash, and any entry with a
 * path. Each of those is a distinct footgun, and each is checked by name so the
 * failure says which one it was.
 */
export function validateOrigins(raw: string | undefined): Set<string> {
  const entries = (raw ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s !== "");

  if (entries.length === 0) {
    throw new ConfigError(
      "ALLOWED_ORIGINS",
      "must list at least one exact origin (PLAN-v3 §3.3)",
    );
  }

  const out = new Set<string>();
  for (const entry of entries) {
    if (entry === "*") {
      throw new ConfigError("ALLOWED_ORIGINS", `wildcard "${entry}" is not permitted`);
    }
    if (entry === "null") {
      throw new ConfigError(
        "ALLOWED_ORIGINS",
        '"null" is not permitted; it is what a sandboxed iframe sends',
      );
    }
    if (entry.endsWith("/")) {
      throw new ConfigError("ALLOWED_ORIGINS", `"${entry}" must not end with a slash`);
    }

    let url: URL;
    try {
      url = new URL(entry);
    } catch {
      throw new ConfigError("ALLOWED_ORIGINS", `"${entry}" is not a URL`);
    }

    if (url.protocol !== "https:") {
      throw new ConfigError(
        "ALLOWED_ORIGINS",
        `"${entry}" must be https; http would put the credential on the wire in clear`,
      );
    }
    // A path (or query, or fragment) makes the origin a prefix, and prefix
    // matching is how an allowlist becomes "any subdomain".
    if (url.pathname !== "/" || url.search !== "" || url.hash !== "") {
      throw new ConfigError(
        "ALLOWED_ORIGINS",
        `"${entry}" must be a bare origin with no path, query or fragment`,
      );
    }

    // A wildcard label is not caught by the bare-origin check: URL happily parses
    // "https://*.example.com" into a hostname of "*.example.com". That value can
    // never match a real Origin header — a browser sends the literal hostname —
    // so accepting it would produce an allowlist entry that silently does
    // nothing, and every request would be refused. Loudly rejected instead.
    if (/[*?]/.test(url.hostname)) {
      throw new ConfigError(
        "ALLOWED_ORIGINS",
        `"${entry}" contains a wildcard label; list each origin exactly`,
      );
    }

    // Normalise to the serialised origin so a configured value and an incoming
    // header compare equal. URL drops the default port, which is the common
    // mismatch ("https://x:443" vs the browser's "https://x").
    out.add(url.origin);
  }

  return out;
}

/** validateSecret checks the CSRF key's shape. */
export function validateSecret(raw: string | undefined, variable = "CSRF_KEY"): string {
  const value = (raw ?? "").trim();
  if (value === "") {
    throw new ConfigError(variable, "is required");
  }
  if (!SECRET_PATTERN.test(value)) {
    throw new ConfigError(
      variable,
      `must be exactly 43 base64url characters (256 bits unpadded), got ${value.length} characters`,
    );
  }
  return value;
}

/**
 * validateInternalOrigin checks the orchestrator URL.
 *
 * It must be https, or http on a name that cannot be a public host — an http URL
 * to a public address would send the HMAC secret in clear on every container
 * creation, which is the one call worth protecting most.
 */
export function validateInternalOrigin(raw: string | undefined): string {
  const value = (raw ?? "").trim();
  if (value === "") {
    throw new ConfigError("ORCHESTRATOR_URL", "is required");
  }
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new ConfigError("ORCHESTRATOR_URL", `"${value}" is not a URL`);
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") {
    throw new ConfigError("ORCHESTRATOR_URL", `"${value}" must be http or https`);
  }
  if (url.protocol === "http:") {
    const host = url.hostname;
    // localhost and single-label names resolve inside the compose network only.
    const internal =
      host === "localhost" ||
      host === "127.0.0.1" ||
      host === "[::1]" ||
      host === "::1" ||
      !host.includes(".");
    if (!internal) {
      throw new ConfigError(
        "ORCHESTRATOR_URL",
        `"${value}" is a public host over http; the HMAC secret would cross the wire in clear. Use https or an internal name`,
      );
    }
  }
  if (url.pathname !== "/") {
    throw new ConfigError("ORCHESTRATOR_URL", `"${value}" must have no path`);
  }
  return url.origin;
}

/** positiveInt reads a positive integer from the environment. */
function positiveInt(
  env: NodeJS.ProcessEnv,
  key: string,
  fallback: number,
): number {
  const raw = env[key]?.trim();
  if (!raw) return fallback;
  const n = Number(raw);
  if (!Number.isInteger(n) || n <= 0) {
    throw new ConfigError(key, `must be a positive integer, got "${raw}"`);
  }
  return n;
}

/** loadConfig validates the whole environment and returns the result. */
export function loadConfig(env: NodeJS.ProcessEnv = process.env): ApiConfig {
  const level = (env.LOG_LEVEL?.trim() || "info") as ApiConfig["logLevel"];
  if (!["debug", "info", "warn", "error"].includes(level)) {
    throw new ConfigError("LOG_LEVEL", `must be debug|info|warn|error, got "${level}"`);
  }

  return {
    allowedOrigins: validateOrigins(env.ALLOWED_ORIGINS),
    csrfKey: validateSecret(env.CSRF_KEY),
    sessionTtlHours: positiveInt(env, "SESSION_TTL_HOURS", 12),
    minFreeDiskMb: positiveInt(env, "MIN_FREE_DISK_MB", 2048),
    orchestratorUrl: validateInternalOrigin(env.ORCHESTRATOR_URL),
    orchestratorSecret: validateSecret(
      env.ORCHESTRATOR_HMAC_SECRET_FILE ? undefined : env.ORCHESTRATOR_HMAC_SECRET,
      "ORCHESTRATOR_HMAC_SECRET",
    ),
    orchestratorReplayWindowSeconds: positiveInt(
      env,
      "ORCHESTRATOR_REPLAY_WINDOW_SECONDS",
      60,
    ),
    logLevel: level,
    listen: env.LISTEN?.trim() || "0.0.0.0:3000",
    databasePath: env.DATABASE_PATH?.trim() || "/srv/msout/data/api.db",
    sseBufferEvents: positiveInt(env, "SSE_BUFFER_EVENTS", 500),
    sseKeepaliveMs: positiveInt(env, "SSE_KEEPALIVE_MS", 15_000),
  };
}